apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-flask
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
  project: default
  source:
    repoURL: https://github.com/meslav-ye/python-app-deployment.git
    targetRevision: main
    path: python-app-service
  destination:
    server: https://kubernetes.default.svc
    namespace: default